volumes:
  pgdata:

services:
  postgres:
    image: postgres:17.3
    container_name: quiz_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quizDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: quiz_redis
    restart: always
    ports:
      - "6379:6379"

