volumes:
  pgdata:

services:
  postgres:
    image: postgres:16
    container_name: quiz_postgres
    restart: always
    environment:
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizpass
      POSTGRES_DB: quizdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: quiz_redis
    restart: always
    ports:
      - "6379:6379"

